#Exp No:10 Experiment to understand array function in Data science.
Description: Understand array function using Numpy library

In [19]:
import numpy as np
array=np.random.randint(1,100,9)
print(array)

[57 99 22 44 98 98 78 91 77]


In [8]:
np.sqrt(array)

array([5.09901951, 6.70820393, 8.1240384 , 9.43398113, 7.93725393,
       8.48528137, 5.29150262, 6.8556546 , 4.        ])

In [9]:
array.ndim

1

In [10]:
new_array=array.reshape(3,3)

In [11]:
new_array.ravel()

array([26, 45, 66, 89, 63, 72, 28, 47, 16])

In [12]:
newm=new_array.reshape(3,3)
newm[2,1:3]
newm[1:2,1:3]

array([[63, 72]])

In [14]:
new_array[0:3,0:0]


array([], shape=(3, 0), dtype=int64)

In [15]:
new_array[0:2,0:1]

array([[26],
       [89]])

In [16]:
new_array[0:3,0:1]

array([[26],
       [89],
       [28]])

In [17]:
new_array[1:3]

array([[89, 63, 72],
       [28, 47, 16]])